/**
 * Tipos de blocos disponíveis no mundo
 * Cada bloco tem propriedades que afetam geração, renderização e física
 */

export const BlockTypes = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  WOOD: 4,
  LEAVES: 5,
  SAND: 6,
  WATER: 7,
  SNOW: 8,
  ICE: 9,
  CLAY: 10,
  GRAVEL: 11,
  COBBLESTONE: 12,
  BEDROCK: 13,
  COAL_ORE: 14,
  IRON_ORE: 15,
  GOLD_ORE: 16,
  DIAMOND_ORE: 17,
  CACTUS: 18,
  DEAD_BUSH: 19,
  FLOWER_RED: 20,
  FLOWER_YELLOW: 21,
  MUSHROOM_RED: 22,
  MUSHROOM_BROWN: 23,
  TALL_GRASS: 24,
  OAK_LOG: 25,
  BIRCH_LOG: 26,
  SPRUCE_LOG: 27,
  OAK_LEAVES: 28,
  BIRCH_LEAVES: 29,
  SPRUCE_LEAVES: 30,
  GLASS: 31,
  BRICK: 32,
};

/**
 * Definições detalhadas de cada tipo de bloco
 */
export const BlockDefinitions = {
  [BlockTypes.AIR]: {
    name: "Ar",
    solid: false,
    transparent: true,
    collidable: false,
    color: null,
  },
  [BlockTypes.GRASS]: {
    name: "Grama",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#567d46",
    textures: {
      top: "grass_top",
      bottom: "dirt",
      sides: "grass_side",
    },
    breakTime: 0.5,
  },
  [BlockTypes.DIRT]: {
    name: "Terra",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#8b6914",
    breakTime: 0.5,
  },
  [BlockTypes.STONE]: {
    name: "Pedra",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#7a7a7a",
    breakTime: 1.5,
  },
  [BlockTypes.WOOD]: {
    name: "Madeira",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#8b5a2b",
    breakTime: 2.0,
  },
  [BlockTypes.LEAVES]: {
    name: "Folhas",
    solid: true,
    transparent: true,
    collidable: true,
    color: "#228b22",
    breakTime: 0.2,
  },
  [BlockTypes.SAND]: {
    name: "Areia",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#e0c090",
    breakTime: 0.5,
    gravity: true,
  },
  [BlockTypes.WATER]: {
    name: "Água",
    solid: false,
    transparent: true,
    collidable: false,
    color: "#3498db",
    opacity: 0.6,
    liquid: true,
  },
  [BlockTypes.SNOW]: {
    name: "Neve",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#f0f0f0",
    breakTime: 0.3,
  },
  [BlockTypes.ICE]: {
    name: "Gelo",
    solid: true,
    transparent: true,
    collidable: true,
    color: "#a5f2f3",
    opacity: 0.8,
    breakTime: 0.5,
  },
  [BlockTypes.CLAY]: {
    name: "Argila",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#9fa4ad",
    breakTime: 0.6,
  },
  [BlockTypes.GRAVEL]: {
    name: "Cascalho",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#808080",
    breakTime: 0.6,
    gravity: true,
  },
  [BlockTypes.COBBLESTONE]: {
    name: "Paralelepípedos",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#5a5a5a",
    breakTime: 2.0,
  },
  [BlockTypes.BEDROCK]: {
    name: "Rocha-mãe",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#1a1a1a",
    breakTime: Infinity,
    indestructible: true,
  },
  [BlockTypes.COAL_ORE]: {
    name: "Carvão",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#2a2a2a",
    breakTime: 3.0,
  },
  [BlockTypes.IRON_ORE]: {
    name: "Ferro",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#b8945f",
    breakTime: 3.0,
  },
  [BlockTypes.GOLD_ORE]: {
    name: "Ouro",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#fcee4b",
    breakTime: 3.0,
  },
  [BlockTypes.DIAMOND_ORE]: {
    name: "Diamante",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#4aedd9",
    breakTime: 5.0,
    emissive: 0.2,
  },
  [BlockTypes.CACTUS]: {
    name: "Cacto",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#0b5d1e",
    breakTime: 0.4,
    damages: true,
  },
  [BlockTypes.DEAD_BUSH]: {
    name: "Arbusto Seco",
    solid: false,
    transparent: true,
    collidable: false,
    color: "#8b7355",
    breakTime: 0,
  },
  [BlockTypes.FLOWER_RED]: {
    name: "Flor Vermelha",
    solid: false,
    transparent: true,
    collidable: false,
    color: "#ff4444",
    breakTime: 0,
  },
  [BlockTypes.FLOWER_YELLOW]: {
    name: "Flor Amarela",
    solid: false,
    transparent: true,
    collidable: false,
    color: "#ffff44",
    breakTime: 0,
  },
  [BlockTypes.MUSHROOM_RED]: {
    name: "Cogumelo Vermelho",
    solid: false,
    transparent: true,
    collidable: false,
    color: "#ff0000",
    breakTime: 0,
  },
  [BlockTypes.MUSHROOM_BROWN]: {
    name: "Cogumelo Marrom",
    solid: false,
    transparent: true,
    collidable: false,
    color: "#8b4513",
    breakTime: 0,
  },
  [BlockTypes.TALL_GRASS]: {
    name: "Grama Alta",
    solid: false,
    transparent: true,
    collidable: false,
    color: "#4a7023",
    breakTime: 0,
  },
  [BlockTypes.OAK_LOG]: {
    name: "Tronco de Carvalho",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#6b4423",
    breakTime: 2.0,
  },
  [BlockTypes.BIRCH_LOG]: {
    name: "Tronco de Bétula",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#d5c4a1",
    breakTime: 2.0,
  },
  [BlockTypes.SPRUCE_LOG]: {
    name: "Tronco de Pinheiro",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#3e2723",
    breakTime: 2.0,
  },
  [BlockTypes.OAK_LEAVES]: {
    name: "Folhas de Carvalho",
    solid: true,
    transparent: true,
    collidable: true,
    color: "#228b22",
    breakTime: 0.2,
  },
  [BlockTypes.BIRCH_LEAVES]: {
    name: "Folhas de Bétula",
    solid: true,
    transparent: true,
    collidable: true,
    color: "#80c622",
    breakTime: 0.2,
  },
  [BlockTypes.SPRUCE_LEAVES]: {
    name: "Folhas de Pinheiro",
    solid: true,
    transparent: true,
    collidable: true,
    color: "#1a472a",
    breakTime: 0.2,
  },
  [BlockTypes.GLASS]: {
    name: "Vidro",
    solid: true,
    transparent: true,
    collidable: true,
    color: "#c8dbe0",
    opacity: 0.3,
    breakTime: 0.3,
  },
  [BlockTypes.BRICK]: {
    name: "Tijolo",
    solid: true,
    transparent: false,
    collidable: true,
    color: "#b75a3c",
    breakTime: 2.0,
  },
};

export default BlockTypes;
